### ISSUE TITLE
Message embedding and text for invalid commands.

### ISSUE THREAD

**Issue by TimmyTradeMark** [TimmyTradeMark/TimmyBot#3]
Hello Kacper, Can you help me on making embedded messages for each commands. and also can you come up with something when someone entered the command, it should show a text that says "This command is invalid"

**Comment by cc0ffee** [comment]
Let me send you something for the error message, not sure when I will have time though @TimmyTradeMark 🙃

**Comment by TimmyTradeMark** [comment]
anytime works.
